### ISSUE TITLE
Unable to start glassfish due to missing password.erb file

### ISSUE THREAD

**Issue by tawrahim** [realityforge/chef-glassfish#54] opened 2015-10-06 17:18 UTC
I have been trying to run glassfish as part of my setup but there seems to be an error with it not being able to find a password.erb file. I am not really doing anything special, just a copy and paste from the README to see if things would work.

Here is my default.rb
```ruby
include_recipe "java"
include_recipe "glassfish::default" 
include_recipe "glassfish::attribute_driven_domain"
```

Here is the relevant content of my vagrant file
```javascript
      "java" => {
        "install_flavor" => "oracle",
        "jdk_version" => "7",
        "oracle" => {
          "accept_oracle_download_terms" => true
        }
      },
      "glassfish" => {
      "version" => "4.0.1",
      "package_url" => "http://download.java.net/glassfish/4.1/release/glassfish-4.1-web.zip",
      "base_dir" => "/usr/local/glassfish",
      "domains_dir" => "/usr/local/glassfish/glassfish/domains",
      "domains" => {
          "myapp" => {
              "config" => {
                  "min_memory" => 1024,
                  "max_memory" => 1024,
                  "max_perm_size" => 256,
                  "port" => 7070,
                  "admin_port" => 4848,
                  "username" => "adminuser",
                  "password" => "adminpw",
                  "master_password" => "mykeystorepassword",
                  "remote_access" => true,
                  "secure" => false
              },
            }
          }
        }
```

Below is the error message
```shell
ERROR: glassfish_domain[myapp] (glassfish::attribute_driven_domain line 267) had an error: RuntimeError: template[/usr/
local/glassfish/glassfish/domains/myapp_admin_passwd] (/tmp/vagrant-chef/15924fc
c9018b85d32864bb35774df22/cookbooks/chef-glassfish/providers/domain.rb line 154)
 had an error: RuntimeError: File templates/default/password.erb does not exist
for cookbook glassfish
```

Is this a known issue or could it be that I am doing something wrong?

**Comment by realityforge** [comment] 2016-07-24 22:54
Firstly - sorry about not responding till now. I did not notice the issue until today.

Secondly - I can't reproduce this with master.  Is this still an issue?

**Comment by realityforge** [comment] 2016-07-24 23:14
Tried a few different approaches and still can't reproduce this. I will close this issue but if you have  steps to reproduce this then we can re-open it.

**Closed by realityforge** 2016-07-24 23:14 UTC
